title: Yifan Guo
email: yifanguo247@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Website for Yifan Guo's interests and works.
baseurl: "/home" # the subpath of your site, e.g. /blog
url: "https://yifanguo247.github.io" # the base hostname & proocol for your site, e.g. http://example.com


 # Build settings
 theme: just-the-docs
 plugins:
  - jekyll-feed

color_scheme: dark
logo: "/assets/images/ml_cover.jpg"

